//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TinyApp.Properties
{
    
    internal partial class Resources
    {
        private static System.Resources.ResourceManager manager;
        internal static System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if ((Resources.manager == null))
                {
                    Resources.manager = new System.Resources.ResourceManager("TinyApp.Properties.Resources", typeof(Resources).Assembly);
                }
                return Resources.manager;
            }
        }
        internal static System.Drawing.Bitmap GetBitmap(Resources.BitmapResources id)
        {
            return ((System.Drawing.Bitmap)(System.Resources.ResourceManager.GetObject(ResourceManager, id)));
        }
        internal static System.Drawing.Font GetFont(Resources.FontResources id)
        {
            return ((System.Drawing.Font)(System.Resources.ResourceManager.GetObject(ResourceManager, id)));
        }
        [System.SerializableAttribute()]
        internal enum FontResources : short
        {
            small = 13070,
            NinaB = 18060,
        }
        [System.SerializableAttribute()]
        internal enum BitmapResources : short
        {
            logo = 17715,
            car = 17810,
            nature = 23172,
        }
    }
}
